apiVersion: apps/v1
kind: Deployment
metadata:
   name: bb-demo
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: springboot
   template:
      metadata:
         labels:
            bb: springboot
      spec:
         containers:
            - name: springboot-site
              image: slaturka/samplespringboot:${{ github.sha }}
              imagePullPolicy: Always              
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/liveness:0.1
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: ItsAlive
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
   name: bb-entrypoint
   namespace: default
spec:
   type: LoadBalancer
   selector:
      bb: springboot
   ports:
      - port: 80
        targetPort: 8082
