apiVersion: apps/v1
kind: Deployment
metadata:
   name: bb-demo
   namespace: zb-poc
spec:
   replicas: 2
   selector:
      matchLabels:
         bb: springboot
   template:
      metadata:
         labels:
            bb: springboot
      spec:
         containers:
            - name: springboot-site
              image: slaturka/samplespringboot:717ab15805bf8d7a42bc971d087e7be1770ceb48
              imagePullPolicy: Always
              
---
apiVersion: v1
kind: Service
metadata:
   name: bb-entrypoint
   namespace: default
spec:
   type: LoadBalancer
   selector:
      bb: springboot
   ports:
      - port: 80
        targetPort: 8082
